blank_issues_enabled: false
contact_links:
  - name: 🔒 Security Vulnerability
    url: mailto:security@tomatenstau.de
    about: Please report security vulnerabilities via email, not GitHub issues
  - name: 💬 General Questions
    url: https://github.com/Paulchenkiller/tomatenstau.de/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/Paulchenkiller/tomatenstau.de/blob/master/README.md
    about: Check the documentation for setup instructions and guidelines
